"""Inital

Revision ID: 881f87e90847
Revises: 937b3ebed043
Create Date: 2024-02-11 02:48:56.265971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '881f87e90847'
down_revision: Union[str, None] = '937b3ebed043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'referal_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('referal_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
